services:
  verranbot:
    image: tabmowtez/verranbot
    restart: unless-stopped
    container_name: verranbot
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 1024M
